version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local-network

  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["sh", "-c", "npm init -y && npm install express && node server.js"]
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
